services:
  mssql-epaa-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_epaa_container_dev
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Developer
      MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
    ports:
      - "1433:1433"
    volumes:
      - /home/sigepaa/mssql/data-dev:/var/opt/mssql/data
      - /home/sigepaa/sigepaa/database/backup-dev:/var/opt/mssql/backup:ro
      - /home/sigepaa/sigepaa/database/scripts:/var/opt/mssql/scripts:ro
    networks:
      - epaa-network-dev

networks:
  epaa-network-dev:
    name: epaa-network-dev
    external: true